Indian Institute of Technology Jodhpur
MLOps


Assignment 1
ML Ops

Submitted by: Jojo Joseph (G23AI2100)


Google Colab : https://colab.research.google.com/drive/16uM0n5-4MNq7Ct540Lkxc2pq_mExswpn?usp=sharing
gitHub : https://github.com/TheJojoJoseph/IITJ_MLOpsAssignment1.git




Q2. For the given data set boston.csv (for each measure MSE and R Sq) (Submit .ipynb files as attachment and screenshots )
# New section

In [ ]:
import numpy as npy
import pandas as pds
import matplotlib.pyplot as pylt
from sklearn.model_selection import train_test_split

In [ ]:
#Import Data from Input
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
dfm = pds.read_csv("/content/drive/My Drive/boston.csv")
dfm.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PT,B,LSTAT,MV
0,0.00632,18.0,2.31,0,0.538,6.575,65.199997,4.0900,1,296,15.300000,396.899994,4.98,24.000000
1,0.02731,0.0,7.07,0,0.469,6.421,78.900002,4.9671,2,242,17.799999,396.899994,9.14,21.600000
2,0.02729,0.0,7.07,0,0.469,7.185,61.099998,4.9671,2,242,17.799999,392.829987,4.03,34.700001
3,0.03237,0.0,2.18,0,0.458,6.998,45.799999,6.0622,3,222,18.700001,394.630005,2.94,33.400002
4,0.06905,0.0,2.18,0,0.458,7.147,54.200001,6.0622,3,222,18.700001,396.899994,5.33,36.200001

In [ ]:
dfm.shape

(506, 14)

In [ ]:
dfm.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PT', 'B', 'LSTAT', 'MV'],
      dtype='object')

In [ ]:
dfm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CRIM    506 non-null    float64
 1   ZN      506 non-null    float64
 2   INDUS   506 non-null    float64
 3   CHAS    506 non-null    int64
 4   NOX     506 non-null    float64
 5   RM      506 non-null    float64
 6   AGE     506 non-null    float64
 7   DIS     506 non-null    float64
 8   RAD     506 non-null    int64
 9   TAX     506 non-null    int64
 10  PT      506 non-null    float64
 11  B       506 non-null    float64
 12  LSTAT   506 non-null    float64
 13  MV      506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [ ]:
#Find Discrete and Continuous variables

dfm["MV"].unique() #NOX, RAD, TAX, PT, CHAS, INDUS, ZN Discrete variable
#RM, AGE, DIS, B, LSTAT, MV, CRIM continues variable

array([24.        , 21.60000038, 34.70000076, 33.40000153, 36.20000076,
       28.70000076, 22.89999962, 27.10000038, 16.5       , 18.89999962,
       15.        , 21.70000076, 20.39999962, 18.20000076, 19.89999962,
       23.10000038, 17.5       , 20.20000076, 13.60000038, 19.60000038,
       15.19999981, 14.5       , 15.60000038, 13.89999962, 16.60000038,
       14.80000019, 18.39999962, 21.        , 12.69999981, 13.19999981,
       13.10000038, 13.5       , 20.        , 24.70000076, 30.79999924,
       34.90000153, 26.60000038, 25.29999924, 21.20000076, 19.29999924,
       14.39999962, 19.39999962, 19.70000076, 20.5       , 25.        ,
       23.39999962, 35.40000153, 31.60000038, 23.29999924, 18.70000076,
       16.        , 22.20000076, 33.        , 23.5       , 22.        ,
       17.39999962, 20.89999962, 24.20000076, 22.79999924, 24.10000038,
       21.39999962, 20.79999924, 20.29999924, 28.        , 23.89999962,
       24.79999924, 22.5       , 23.60000038, 22.60000038, 20.60000038,
       28.39999962, 38.70000076, 43.79999924, 33.20000076, 27.5       ,
       26.5       , 18.60000038, 20.10000038, 19.5       , 19.79999924,
       18.79999924, 18.5       , 18.29999924, 19.20000076, 17.29999924,
       15.69999981, 16.20000076, 18.        , 14.30000019, 23.        ,
       18.10000038, 17.10000038, 13.30000019, 17.79999924, 14.        ,
       13.39999962, 11.80000019, 13.80000019, 14.60000038, 15.39999962,
       21.5       , 15.30000019, 17.        , 41.29999924, 24.29999924,
       27.        , 50.        , 22.70000076, 23.79999924, 22.29999924,
       19.10000038, 29.39999962, 23.20000076, 24.60000038, 29.89999962,
       37.20000076, 39.79999924, 37.90000153, 32.5       , 26.39999962,
       29.60000038, 32.        , 29.79999924, 37.        , 30.5       ,
       36.40000153, 31.10000038, 29.10000038, 33.29999924, 30.29999924,
       34.59999847, 32.90000153, 42.29999924, 48.5       , 24.39999962,
       22.39999962, 28.10000038, 23.70000076, 26.70000076, 30.10000038,
       44.79999924, 37.59999847, 46.70000076, 31.5       , 31.70000076,
       41.70000076, 48.29999924, 29.        , 25.10000038, 17.60000038,
       24.5       , 26.20000076, 42.79999924, 21.89999962, 44.        ,
       36.        , 33.79999924, 43.09999847, 48.79999924, 31.        ,
       36.5       , 30.70000076, 43.5       , 20.70000076, 21.10000038,
       25.20000076, 35.20000076, 32.40000153, 33.09999847, 35.09999847,
       45.40000153, 46.        , 32.20000076, 28.5       , 37.29999924,
       27.89999962, 28.60000038, 36.09999847, 28.20000076, 16.10000038,
       22.10000038, 19.        , 32.70000076, 31.20000076, 17.20000076,
       16.79999924, 10.19999981, 10.39999962, 10.89999962, 11.30000019,
       12.30000019,  8.80000019,  7.19999981, 10.5       ,  7.4000001 ,
       11.5       , 15.10000038,  9.69999981, 12.5       ,  8.5       ,
        5.        ,  6.30000019,  5.5999999 , 12.10000038,  8.30000019,
       11.89999962, 17.89999962, 16.29999924,  7.        ,  7.5       ,
        8.39999962, 16.70000076, 14.19999981, 11.69999981, 11.        ,
        9.5       , 14.10000038,  9.60000038,  8.69999981, 12.80000019,
       10.80000019, 14.89999962, 12.60000038, 13.        , 16.39999962,
       17.70000076, 12.        , 21.79999924,  8.10000038])

In [ ]:
dfm["CHAS"].unique() #Discrete variable

array([0, 1])

In [ ]:
dfm["INDUS"].unique() #Discrete variable

array([ 2.30999994,  7.07000017,  2.18000007,  7.86999989,  8.14000034,
        5.96000004,  2.95000005,  6.90999985,  5.63999987,  4.        ,
        1.22000003,  0.74000001,  1.32000005,  5.13000011,  1.37999999,
        3.36999989,  6.07000017, 10.81000042, 12.82999992,  4.86000013,
        4.48999977,  3.41000009, 15.03999996,  2.8900001 ,  8.56000042,
       10.01000023, 25.64999962, 21.88999939, 19.57999992,  4.05000019,
        2.46000004,  3.44000006,  2.93000007,  0.46000001,  1.51999998,
        1.47000003,  2.02999997,  2.68000007, 10.59000015, 13.89000034,
        6.19999981,  4.92999983,  5.86000013,  3.6400001 ,  3.75      ,
        3.97000003,  6.96000004,  6.40999985,  3.32999992,  1.21000004,
        2.97000003,  2.25      ,  1.75999999,  5.32000017,  4.94999981,
       13.92000008,  2.24000001,  6.09000015,  9.89999962,  7.38000011,
        3.24000001,  6.05999994,  5.19000006,  1.88999999,  3.77999997,
        4.38999987,  4.1500001 ,  2.00999999,  1.25      ,  1.69000006,
        2.01999998,  1.90999997, 18.10000038, 27.73999977,  9.68999958,
       11.93000031])

In [ ]:
dfm["CRIM"].unique() #continues variable

array([6.32000000e-03, 2.73100010e-02, 2.72900000e-02, 3.23700010e-02,
       6.90499990e-02, 2.98500010e-02, 8.82899980e-02, 1.44549996e-01,
       2.11239994e-01, 1.70039997e-01, 2.24889994e-01, 1.17470004e-01,
       9.37800030e-02, 6.29760027e-01, 6.37960017e-01, 6.27390027e-01,
       1.05393004e+00, 7.84200013e-01, 8.02709997e-01, 7.25799978e-01,
       1.25179005e+00, 8.52039993e-01, 1.23247004e+00, 9.88430023e-01,
       7.50259995e-01, 8.40539992e-01, 6.71909988e-01, 9.55770016e-01,
       7.72989988e-01, 1.00244999e+00, 1.13081002e+00, 1.35472000e+00,
       1.38799000e+00, 1.15172005e+00, 1.61282003e+00, 6.41700030e-02,
       9.74399970e-02, 8.01400020e-02, 1.75050005e-01, 2.76299990e-02,
       3.35900000e-02, 1.27440006e-01, 1.41499996e-01, 1.59360006e-01,
       1.22690000e-01, 1.71419993e-01, 1.88360006e-01, 2.29269996e-01,
       2.53870010e-01, 2.19769999e-01, 8.87300000e-02, 4.33700010e-02,
       5.35999980e-02, 4.98100000e-02, 1.36000000e-02, 1.31100000e-02,
       2.05500000e-02, 1.43200000e-02, 1.54449999e-01, 1.03280000e-01,
       1.49320006e-01, 1.71709999e-01, 1.10270001e-01, 1.26499996e-01,
       1.95099990e-02, 3.58400010e-02, 4.37900010e-02, 5.78900020e-02,
       1.35539994e-01, 1.28160000e-01, 8.82600020e-02, 1.58759996e-01,
       9.16400030e-02, 1.95390001e-01, 7.89600010e-02, 9.51199980e-02,
       1.01530001e-01, 8.70700030e-02, 5.64600010e-02, 8.38700010e-02,
       4.11299990e-02, 4.46200000e-02, 3.65899990e-02, 3.55100000e-02,
       5.05900010e-02, 5.73499990e-02, 5.18799980e-02, 7.15100020e-02,
       5.66000010e-02, 5.30200000e-02, 4.68400010e-02, 3.93200000e-02,
       4.20299990e-02, 2.87500010e-02, 4.29399980e-02, 1.22040004e-01,
       1.15039997e-01, 1.20829999e-01, 8.18699970e-02, 6.85999990e-02,
       1.48660004e-01, 1.14320002e-01, 2.28760004e-01, 2.11610004e-01,
       1.39599994e-01, 1.32620007e-01, 1.71200007e-01, 1.31170005e-01,
       1.28020003e-01, 2.63630003e-01, 1.07929997e-01, 1.00840002e-01,
       1.23290002e-01, 2.22120002e-01, 1.42309994e-01, 1.71340004e-01,
       1.31579995e-01, 1.50979996e-01, 1.30579993e-01, 1.44759998e-01,
       6.89900000e-02, 7.16499980e-02, 9.29900040e-02, 1.50380000e-01,
       9.84900000e-02, 1.69019997e-01, 3.87349993e-01, 2.59149998e-01,
       3.25430006e-01, 8.81250024e-01, 3.40059996e-01, 1.19294000e+00,
       5.90049982e-01, 3.29820007e-01, 9.76170003e-01, 5.57780027e-01,
       3.22640002e-01, 3.52329999e-01, 2.49799997e-01, 5.44520020e-01,
       2.90899992e-01, 1.62864006e+00, 3.32104993e+00, 4.09740019e+00,
       2.77974010e+00, 2.37933993e+00, 2.15505004e+00, 2.36861992e+00,
       2.33099008e+00, 2.73396993e+00, 1.65660000e+00, 1.49632001e+00,
       1.12658000e+00, 2.14917993e+00, 1.41384995e+00, 3.53501010e+00,
       2.44668007e+00, 1.22358000e+00, 1.34283996e+00, 1.42501998e+00,
       1.27346003e+00, 1.46335995e+00, 1.83377004e+00, 1.51901996e+00,
       2.24236011e+00, 2.92400002e+00, 2.01019001e+00, 1.80027998e+00,
       2.30040002e+00, 2.44952989e+00, 1.20741999e+00, 2.31389999e+00,
       1.39139995e-01, 9.17799990e-02, 8.44699960e-02, 6.66399970e-02,
       7.02200010e-02, 5.42499980e-02, 6.64199960e-02, 5.77999990e-02,
       6.58800010e-02, 6.88799990e-02, 9.10300020e-02, 1.00079998e-01,
       8.30800010e-02, 6.04700000e-02, 5.60199990e-02, 7.87499990e-02,
       1.25790000e-01, 8.37000010e-02, 9.06800030e-02, 6.91099990e-02,
       8.66400000e-02, 2.18700000e-02, 1.43900000e-02, 1.38100000e-02,
       4.01099990e-02, 4.66599990e-02, 3.76800000e-02, 3.15000010e-02,
       1.77800000e-02, 3.44499980e-02, 2.17700000e-02, 3.51000020e-02,
       2.00900010e-02, 1.36419997e-01, 2.29690000e-01, 2.51989990e-01,
       1.35869995e-01, 4.35710013e-01, 1.74459994e-01, 3.75779986e-01,
       2.17189997e-01, 1.40520006e-01, 2.89550006e-01, 1.98019996e-01,
       4.56000010e-02, 7.01299980e-02, 1.10689998e-01, 1.14249997e-01,
       3.58090013e-01, 4.07709986e-01, 6.23560011e-01, 6.14700019e-01,
       3.15329999e-01, 5.26929975e-01, 3.82140011e-01, 4.12380010e-01,
       2.98189998e-01, 4.41780001e-01, 5.37000000e-01, 4.62960005e-01,
       5.75290024e-01, 3.31470013e-01, 4.47910011e-01, 3.30449998e-01,
       5.20579994e-01, 5.11829972e-01, 8.24399960e-02, 9.25199990e-02,
       1.13289997e-01, 1.06119998e-01, 1.02899998e-01, 1.27570003e-01,
       2.06080005e-01, 1.91330001e-01, 3.39830011e-01, 1.96569994e-01,
       1.64389998e-01, 1.90730006e-01, 1.40300006e-01, 2.14090005e-01,
       8.22099970e-02, 3.68939996e-01, 4.81900010e-02, 3.54800000e-02,
       1.53800000e-02, 6.11540020e-01, 6.63510025e-01, 6.56650007e-01,
       5.40109992e-01, 5.34120023e-01, 5.20139992e-01, 8.25259984e-01,
       5.50069988e-01, 7.61619985e-01, 7.85700023e-01, 5.78339994e-01,
       5.40499985e-01, 9.06500000e-02, 2.99160004e-01, 1.62110001e-01,
       1.14600003e-01, 2.21880004e-01, 5.64399990e-02, 9.60400030e-02,
       1.04690000e-01, 6.12699990e-02, 7.97799970e-02, 2.10380003e-01,
       3.57800010e-02, 3.70500010e-02, 6.12900000e-02, 1.50100000e-02,
       9.06000000e-03, 1.09600000e-02, 1.96499990e-02, 3.87100020e-02,
       4.58999980e-02, 4.29700020e-02, 3.50200010e-02, 7.88600000e-02,
       3.61500010e-02, 8.26499980e-02, 8.19900040e-02, 1.29319996e-01,
       5.37200010e-02, 1.41029999e-01, 6.46599980e-02, 5.56100010e-02,
       4.41700000e-02, 3.53700000e-02, 9.26600020e-02, 1.00000001e-01,
       5.51499990e-02, 5.47900010e-02, 7.50299990e-02, 4.93200010e-02,
       4.92980003e-01, 3.49400014e-01, 2.63547993e+00, 7.90409982e-01,
       2.61689991e-01, 2.69380003e-01, 3.69199991e-01, 2.53560007e-01,
       3.18269998e-01, 2.45220006e-01, 4.02020007e-01, 4.75470006e-01,
       1.67600006e-01, 1.81590006e-01, 3.51139992e-01, 2.83919990e-01,
       3.41089994e-01, 1.91860005e-01, 3.03469986e-01, 2.41029993e-01,
       6.61700000e-02, 6.72400000e-02, 4.54400000e-02, 5.02300000e-02,
       3.46600000e-02, 5.08299990e-02, 3.73799990e-02, 3.96099980e-02,
       3.42700000e-02, 3.04099990e-02, 3.30599990e-02, 5.49700000e-02,
       6.15100000e-02, 1.30100000e-02, 2.49799990e-02, 2.54299990e-02,
       3.04900000e-02, 3.11299990e-02, 6.16200010e-02, 1.87000000e-02,
       2.89900000e-02, 6.21099990e-02, 7.94999970e-02, 7.24399980e-02,
       1.70900000e-02, 4.30100000e-02, 1.06590003e-01, 8.98295975e+00,
       3.84969997e+00, 5.20176983e+00, 4.26131010e+00, 4.54192019e+00,
       3.83683991e+00, 3.67822003e+00, 4.22239018e+00, 3.47428012e+00,
       4.55587006e+00, 3.69694996e+00, 1.35221996e+01, 4.89822006e+00,
       5.66998005e+00, 6.53876019e+00, 9.23229981e+00, 8.26725006e+00,
       1.11080999e+01, 1.84981995e+01, 1.96091003e+01, 1.52880001e+01,
       9.82349014e+00, 2.36481991e+01, 1.78666992e+01, 8.89761963e+01,
       1.58744001e+01, 9.18702030e+00, 7.99247980e+00, 2.00848999e+01,
       1.68118000e+01, 2.43938007e+01, 2.25970993e+01, 1.43337002e+01,
       8.15174007e+00, 6.96215010e+00, 5.29304981e+00, 1.15778999e+01,
       8.64476013e+00, 1.33598003e+01, 8.71675015e+00, 5.87204981e+00,
       7.67201996e+00, 3.83517990e+01, 9.91654968e+00, 2.50461006e+01,
       1.42362003e+01, 9.59570980e+00, 2.48017006e+01, 4.15292015e+01,
       6.79207993e+01, 2.07161999e+01, 1.19511004e+01, 7.40389013e+00,
       1.44383001e+01, 5.11357994e+01, 1.40507002e+01, 1.88110008e+01,
       2.86557999e+01, 4.57461014e+01, 1.80846004e+01, 1.08341999e+01,
       2.59405994e+01, 7.35341034e+01, 1.18122997e+01, 1.10874004e+01,
       7.02259016e+00, 1.20481997e+01, 7.05041981e+00, 8.79211998e+00,
       1.58603001e+01, 1.22472000e+01, 3.76618996e+01, 7.36710978e+00,
       9.33889008e+00, 8.49213028e+00, 1.00622997e+01, 6.44404984e+00,
       5.58106995e+00, 1.39133997e+01, 1.11604004e+01, 1.44208002e+01,
       1.51772003e+01, 1.36780996e+01, 9.39062977e+00, 2.20510998e+01,
       9.72418022e+00, 5.66636991e+00, 9.96654034e+00, 1.28023005e+01,
       1.06717997e+01, 6.28807020e+00, 9.92485046e+00, 9.32909012e+00,
       7.52601004e+00, 6.71772003e+00, 5.44114018e+00, 5.09016991e+00,
       8.24808979e+00, 9.51362991e+00, 4.75236988e+00, 4.66882992e+00,
       8.20057964e+00, 7.75223017e+00, 6.80116987e+00, 4.81212997e+00,
       3.69310999e+00, 6.65492010e+00, 5.82114983e+00, 7.83932018e+00,
       3.16359997e+00, 3.77498007e+00, 4.42227984e+00, 1.55756998e+01,
       1.30751000e+01, 4.34879017e+00, 4.03841019e+00, 3.56868005e+00,
       4.64689016e+00, 8.05578995e+00, 6.39311981e+00, 4.87140989e+00,
       1.50234003e+01, 1.02329998e+01, 5.82400989e+00, 5.70817995e+00,
       5.73116016e+00, 2.81838012e+00, 2.37857008e+00, 3.67367005e+00,
       5.69175005e+00, 4.83566999e+00, 1.50859997e-01, 1.83369994e-01,
       2.07460001e-01, 1.05740003e-01, 1.11319996e-01, 1.73309997e-01,
       2.79570013e-01, 1.78990006e-01, 2.89600015e-01, 2.68379986e-01,
       2.39120007e-01, 1.77829996e-01, 2.24380001e-01, 6.26299980e-02,
       4.52700000e-02, 6.07599990e-02, 1.09590001e-01, 4.74100000e-02])

In [ ]:
dfm["ZN"].unique() #Discrete variable

array([ 18. ,   0. ,  12.5,  75. ,  21. ,  90. ,  85. , 100. ,  25. ,
        17.5,  80. ,  28. ,  45. ,  60. ,  95. ,  82.5,  30. ,  22. ,
        20. ,  40. ,  55. ,  52.5,  70. ,  34. ,  33. ,  35. ])

In [ ]:
dfm.corr()
#TAX and RAD are highly correlated.

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PT,B,LSTAT,MV
CRIM,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
ZN,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
INDUS,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
CHAS,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260
NOX,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
RM,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355502,0.128069,-0.613808,0.695360
AGE,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
DIS,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
RAD,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
TAX,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
PT,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355502,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
B,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
LSTAT,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
MV,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000

In [ ]:
dfm = dfm.drop(columns=['RAD'])
dfm.shape

(506, 13)

In [ ]:
npy.percentile(dfm["CRIM"],25)

0.08204500225

In [ ]:
for clm in dfm.columns:
    print(f"Descriptive Analytics for Column: {clm}")
    print(dfm[clm].describe())  # Descriptive statistics
    print("\n" + "-"*50 + "\n")  # Separator for readability

Descriptive Analytics for Column: CRIM
count    506.000000
mean       3.613524
std        8.601545
min        0.006320
25%        0.082045
50%        0.256510
75%        3.677083
max       88.976196
Name: CRIM, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: ZN
count    506.000000
mean      11.363636
std       23.322453
min        0.000000
25%        0.000000
50%        0.000000
75%       12.500000
max      100.000000
Name: ZN, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: INDUS
count    506.000000
mean      11.136779
std        6.860353
min        0.460000
25%        5.190000
50%        9.690000
75%       18.100000
max       27.740000
Name: INDUS, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: CHAS
count    506.000000
mean       0.069170
std        0.253994
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
Name: CHAS, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: NOX
count    506.000000
mean       0.554695
std        0.115878
min        0.385000
25%        0.449000
50%        0.538000
75%        0.624000
max        0.871000
Name: NOX, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: RM
count    506.000000
mean       6.284634
std        0.702617
min        3.561000
25%        5.885500
50%        6.208500
75%        6.623500
max        8.780000
Name: RM, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: AGE
count    506.000000
mean      68.574901
std       28.148862
min        2.900000
25%       45.025000
50%       77.500000
75%       94.074999
max      100.000000
Name: AGE, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: DIS
count    506.000000
mean       3.795043
std        2.105710
min        1.129600
25%        2.100175
50%        3.207450
75%        5.188425
max       12.126500
Name: DIS, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: TAX
count    506.000000
mean     408.237154
std      168.537116
min      187.000000
25%      279.000000
50%      330.000000
75%      666.000000
max      711.000000
Name: TAX, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: PT
count    506.000000
mean      18.455534
std        2.164946
min       12.600000
25%       17.400000
50%       19.050000
75%       20.200001
max       22.000000
Name: PT, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: B
count    506.000000
mean     356.674030
std       91.294863
min        0.320000
25%      375.377487
50%      391.440002
75%      396.225006
max      396.899994
Name: B, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: LSTAT
count    506.000000
mean      12.653063
std        7.141062
min        1.730000
25%        6.950000
50%       11.360000
75%       16.954999
max       37.970001
Name: LSTAT, dtype: float64

--------------------------------------------------

Descriptive Analytics for Column: MV
count    506.000000
mean      22.532806
std        9.197104
min        5.000000
25%       17.025000
50%       21.200001
75%       25.000000
max       50.000000
Name: MV, dtype: float64

--------------------------------------------------

In [ ]:
dfm["LSTAT"].describe()

count    506.000000
mean      12.653063
std        7.141062
min        1.730000
25%        6.950000
50%       11.360000
75%       16.954999
max       37.970001
Name: LSTAT, dtype: float64

In [ ]:
dfm["B"].describe()

count    506.000000
mean     356.674030
std       91.294863
min        0.320000
25%      375.377487
50%      391.440002
75%      396.225006
max      396.899994
Name: B, dtype: float64

In [ ]:
dfm["DIS"].describe()

count    506.000000
mean       3.795043
std        2.105710
min        1.129600
25%        2.100175
50%        3.207450
75%        5.188425
max       12.126500
Name: DIS, dtype: float64

In [ ]:
dfm["AGE"].describe()

count    506.000000
mean      68.574901
std       28.148862
min        2.900000
25%       45.025000
50%       77.500000
75%       94.074999
max      100.000000
Name: AGE, dtype: float64

In [ ]:
dfm["RM"].describe()

count    506.000000
mean       6.284634
std        0.702617
min        3.561000
25%        5.885500
50%        6.208500
75%        6.623500
max        8.780000
Name: RM, dtype: float64

In [ ]:
dfm["PT"].describe()

count    506.000000
mean      18.455534
std        2.164946
min       12.600000
25%       17.400000
50%       19.050000
75%       20.200001
max       22.000000
Name: PT, dtype: float64

In [ ]:
dfm["ZN"].describe()

count    506.000000
mean      11.363636
std       23.322453
min        0.000000
25%        0.000000
50%        0.000000
75%       12.500000
max      100.000000
Name: ZN, dtype: float64

In [ ]:
dfm["INDUS"].describe()

count    506.000000
mean      11.136779
std        6.860353
min        0.460000
25%        5.190000
50%        9.690000
75%       18.100000
max       27.740000
Name: INDUS, dtype: float64

In [ ]:
dfm["CHAS"].describe()

count    506.000000
mean       0.069170
std        0.253994
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
Name: CHAS, dtype: float64

In [ ]:
dfm["NOX"].describe()

count    506.000000
mean       0.554695
std        0.115878
min        0.385000
25%        0.449000
50%        0.538000
75%        0.624000
max        0.871000
Name: NOX, dtype: float64

In [ ]:
dfm["TAX"].describe()

count    506.000000
mean     408.237154
std      168.537116
min      187.000000
25%      279.000000
50%      330.000000
75%      666.000000
max      711.000000
Name: TAX, dtype: float64

In [ ]:
dfm["CRIM"].describe()

count    506.000000
mean       3.613524
std        8.601545
min        0.006320
25%        0.082045
50%        0.256510
75%        3.677083
max       88.976196
Name: CRIM, dtype: float64

Generate a linear regression program for the dataset (MV is the output value)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
x = dfm.drop(columns=['MV'])
y = dfm['MV']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
# Create a Linear Regression model
Model = LinearRegression()

In [ ]:
Model.fit(X_train, y_train)

# Predict on the test set
y_pred = Model.predict(X_test)

In [ ]:
MSE = mean_squared_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
print("Mean Squared Error (MSE):", MSE)
print("R-Squared (R²):", R2)

Mean Squared Error (MSE): 26.47094373249293
R-Squared (R²): 0.6390348062671878

Normalize the input fields and generate a SGD regressor for the same and find R – Square.

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
x = dfm.drop(columns=['MV'])
y = dfm['MV']
# Normalize the input features
Scaler = StandardScaler()
X_scaled = Scaler.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
sgd_regressor = SGDRegressor(max_iter=1000, tol=1e-3, random_state=42)

sgd_regressor.fit(X_train, y_train)

y_pred = sgd_regressor.predict(X_test)

In [ ]:
MSE = mean_squared_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)

# Display results
print("Mean Squared Error (MSE):", MSE)
print("R-Squared (R²):", R2)

Mean Squared Error (MSE): 26.68205970643862
R-Squared (R²): 0.6361559697887642

In [ ]:
import pandas as pds
import numpy as npy
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import SGDRegressor, LinearRegression
from sklearn.metrics import mean_squared_error, r2_score



# Define features (X) and target (y)
X = dfm.drop(columns=["MV"], axis=1)
y = dfm["MV"]

# Standardize the features
Scaler = StandardScaler()
X_scaled = Scaler.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Initialize lists to store results
Components_List = range(1, X.shape[1] + 1)
sgd_mse, sgd_r2, linreg_mse, linreg_r2 = [], [], [], []

for n_components in Components_List:
    # Apply PCA
    pca = PCA(n_components=n_components)
    X_train_pca = pca.fit_transform(X_train)
    X_test_pca = pca.transform(X_test)

    # Linear Regression
    linreg = LinearRegression()
    linreg.fit(X_train_pca, y_train)
    y_pred_linreg = linreg.predict(X_test_pca)
    linreg_mse.append(mean_squared_error(y_test, y_pred_linreg))
    linreg_r2.append(r2_score(y_test, y_pred_linreg))

    # SGD Regressor
    sgd = SGDRegressor(max_iter=1000, tol=1e-3, random_state=42)
    sgd.fit(X_train_pca, y_train)
    y_pred_sgd = sgd.predict(X_test_pca)
    sgd_mse.append(mean_squared_error(y_test, y_pred_sgd))
    sgd_r2.append(r2_score(y_test, y_pred_sgd))

# Print the results
print("\nResults with Varying Number of PCA Components:\n")
print("Components\tLinear Regression MSE\tLinear Regression R2\tSGD MSE\tSGD R2")
for i, n in enumerate(Components_List):
    print(f"{n}\t\t{linreg_mse[i]:.4f}\t\t{linreg_r2[i]:.4f}\t\t{sgd_mse[i]:.4f}\t\t{sgd_r2[i]:.4f}")

Results with Varying Number of PCA Components:

Components	Linear Regression MSE	Linear Regression R2	SGD MSE	SGD R2
1		39.9893		0.4547		39.9882		0.4547
2		34.1245		0.5347		33.9756		0.5367
3		29.5241		0.5974		29.4339		0.5986
4		28.2844		0.6143		28.3277		0.6137
5		30.0843		0.5898		30.1588		0.5887
6		29.8188		0.5934		29.8853		0.5925
7		29.8093		0.5935		29.8798		0.5926
8		29.7089		0.5949		29.7422		0.5944
9		28.5572		0.6106		28.6777		0.6089
10		28.7325		0.6082		28.8298		0.6069
11		27.0729		0.6308		27.2941		0.6278
12		26.4709		0.6390		26.7404		0.6354

In [ ]:
import pandas as pds
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score



# Identify discrete variables (for simplicity, assuming integer types are discrete)
discrete_cols = dfm.select_dtypes(include=['int64']).columns.tolist()

#discrete_cols.remove("MV")  # Exclude the target variable

# One-Hot Encoding of discrete variables
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoded_features = encoder.fit_transform(dfm[discrete_cols])
encoded_feature_names = encoder.get_feature_names_out(discrete_cols)

# Combine the encoded features with the continuous ones
continuous_cols = dfm.drop(columns=discrete_cols + ["MV"], axis=1).columns
data_encoded = pds.DataFrame(encoded_features, columns=encoded_feature_names)
data_continuous = dfm[continuous_cols].reset_index(drop=True)
X = pds.concat([data_continuous, data_encoded], axis=1)
y = dfm["MV"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the continuous features
scaler = StandardScaler()
X_train[continuous_cols] = scaler.fit_transform(X_train[continuous_cols])
X_test[continuous_cols] = scaler.transform(X_test[continuous_cols])

# Train Linear Regression
linreg = LinearRegression()
linreg.fit(X_train, y_train)

# Predict and Evaluate
y_pred = linreg.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print Results
print(f"Mean Squared Error: {mse:.4f}")
print(f"R-Square: {r2:.4f}")

Mean Squared Error: 22.3439
R-Square: 0.6953

In [ ]:
pip install optuna

Collecting optuna
  Downloading optuna-4.1.0-py3-none-any.whl.metadata (16 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.14.0-py3-none-any.whl.metadata (7.4 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.10/dist-packages (from optuna) (2.0.36)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from optuna) (4.66.6)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from optuna) (6.0.2)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading Mako-1.3.8-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.1.0-py3-none-any.whl (364 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 364.4/364.4 kB 7.0 MB/s eta 0:00:00
Downloading alembic-1.14.0-py3-none-any.whl (233 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.5/233.5 kB 16.1 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Downloading Mako-1.3.8-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 5.6 MB/s eta 0:00:00
Installing collected packages: Mako, colorlog, alembic, optuna
Successfully installed Mako-1.3.8 alembic-1.14.0 colorlog-6.9.0 optuna-4.1.0

In [ ]:
import optuna
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
import pandas as pds
import numpy as npy


X = dfm.drop(columns=["MV"], axis=1)
y = dfm["MV"]

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardization pipeline
Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

# Define objective functions for each model

def knn_objective(trial):
    n_neighbors = trial.suggest_int("n_neighbors", 1, 20)
    weights = trial.suggest_categorical("weights", ["uniform", "distance"])
    p = trial.suggest_int("p", 1, 2)

    model = KNeighborsRegressor(n_neighbors=n_neighbors, weights=weights, p=p)
    score = cross_val_score(model, X_train, y_train, scoring="neg_mean_squared_error", cv=5).mean()
    return -score

def rf_objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 3, 20)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)

    model = RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth, min_samples_split=min_samples_split, random_state=42)
    score = cross_val_score(model, X_train, y_train, scoring="neg_mean_squared_error", cv=5).mean()
    return -score

def ridge_objective(trial):
    alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)

    model = Ridge(alpha=alpha)
    score = cross_val_score(model, X_train, y_train, scoring="neg_mean_squared_error", cv=5).mean()
    return -score

# Run Optuna for each model
print("Optimizing KNN...")
study_knn = optuna.create_study(direction="minimize")
study_knn.optimize(knn_objective, n_trials=50)

print("Optimizing Random Forest...")
study_rf = optuna.create_study(direction="minimize")
study_rf.optimize(rf_objective, n_trials=50)

print("Optimizing Ridge...")
study_ridge = optuna.create_study(direction="minimize")
study_ridge.optimize(ridge_objective, n_trials=50)

# Print the best parameters and scores
print("Best parameters for KNN:", study_knn.best_params)
print("Best score for KNN:", study_knn.best_value)

print("Best parameters for Random Forest:", study_rf.best_params)
print("Best score for Random Forest:", study_rf.best_value)

print("Best parameters for Ridge:", study_ridge.best_params)
print("Best score for Ridge:", study_ridge.best_value)

[I 2024-12-12 13:59:27,263] A new study created in memory with name: no-name-0e506480-9f2b-4463-8d06-945ff316178d
[I 2024-12-12 13:59:27,286] Trial 0 finished with value: 20.332625149975343 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'p': 2}. Best is trial 0 with value: 20.332625149975343.
[I 2024-12-12 13:59:27,307] Trial 1 finished with value: 25.00768398966981 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'p': 2}. Best is trial 0 with value: 20.332625149975343.
[I 2024-12-12 13:59:27,325] Trial 2 finished with value: 21.828220354740026 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 0 with value: 20.332625149975343.
[I 2024-12-12 13:59:27,346] Trial 3 finished with value: 17.43309312632365 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 1}. Best is trial 3 with value: 17.43309312632365.
[I 2024-12-12 13:59:27,366] Trial 4 finished with value: 15.739524325431393 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,384] Trial 5 finished with value: 18.517979662048322 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,405] Trial 6 finished with value: 26.24517129380747 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,426] Trial 7 finished with value: 21.981054852774857 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,447] Trial 8 finished with value: 18.517979662048322 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 1}. Best is trial 4 with value: 15.739524325431393.

Optimizing KNN...

[I 2024-12-12 13:59:27,467] Trial 9 finished with value: 19.88597107993739 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,495] Trial 10 finished with value: 19.187661378978063 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,525] Trial 11 finished with value: 19.085915578229837 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,553] Trial 12 finished with value: 18.378590359788397 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,583] Trial 13 finished with value: 17.43309312632365 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,611] Trial 14 finished with value: 19.655145685011586 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,644] Trial 15 finished with value: 19.958850484749874 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,674] Trial 16 finished with value: 18.21902278018648 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,703] Trial 17 finished with value: 16.467725520454326 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,733] Trial 18 finished with value: 16.467725520454326 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,763] Trial 19 finished with value: 16.707481132029876 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,798] Trial 20 finished with value: 19.914145870429056 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,836] Trial 21 finished with value: 16.467725520454326 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,879] Trial 22 finished with value: 16.467725520454326 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,913] Trial 23 finished with value: 17.91010874510609 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,951] Trial 24 finished with value: 21.828220354740022 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:27,988] Trial 25 finished with value: 22.45405879985296 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,022] Trial 26 finished with value: 18.45373496641499 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,060] Trial 27 finished with value: 16.467725520454326 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,088] Trial 28 finished with value: 18.27571008724474 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,116] Trial 29 finished with value: 17.754877151774032 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,145] Trial 30 finished with value: 20.852270892154735 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,173] Trial 31 finished with value: 16.467725520454326 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,200] Trial 32 finished with value: 16.707481132029876 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,228] Trial 33 finished with value: 16.707481132029876 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,284] Trial 34 finished with value: 22.252196749421664 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,336] Trial 35 finished with value: 18.33368348794024 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,372] Trial 36 finished with value: 21.828220354740026 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,409] Trial 37 finished with value: 17.754877151774032 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,445] Trial 38 finished with value: 18.787747462977936 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,483] Trial 39 finished with value: 16.48241740998341 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,509] Trial 40 finished with value: 17.502687893831805 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,541] Trial 41 finished with value: 16.467725520454326 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,568] Trial 42 finished with value: 17.754877151774032 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,595] Trial 43 finished with value: 21.828220354740022 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,621] Trial 44 finished with value: 18.27571008724474 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,646] Trial 45 finished with value: 16.467725520454326 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,674] Trial 46 finished with value: 15.739524325431393 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,704] Trial 47 finished with value: 18.21902278018648 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,731] Trial 48 finished with value: 19.085915578229837 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,759] Trial 49 finished with value: 19.88597107993739 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 1}. Best is trial 4 with value: 15.739524325431393.
[I 2024-12-12 13:59:28,760] A new study created in memory with name: no-name-5334da5b-11b2-461c-b6aa-a3471b5ca7ad

Optimizing Random Forest...

[I 2024-12-12 13:59:30,127] Trial 0 finished with value: 15.215648183011933 and parameters: {'n_estimators': 106, 'max_depth': 18, 'min_samples_split': 9}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:32,981] Trial 1 finished with value: 15.390858130022428 and parameters: {'n_estimators': 179, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:35,957] Trial 2 finished with value: 15.371668409159735 and parameters: {'n_estimators': 191, 'max_depth': 18, 'min_samples_split': 10}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:39,386] Trial 3 finished with value: 15.263522467308743 and parameters: {'n_estimators': 187, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:40,731] Trial 4 finished with value: 15.91682265424753 and parameters: {'n_estimators': 93, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:41,464] Trial 5 finished with value: 16.081591204826704 and parameters: {'n_estimators': 36, 'max_depth': 20, 'min_samples_split': 7}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:46,028] Trial 6 finished with value: 15.376688771088464 and parameters: {'n_estimators': 136, 'max_depth': 18, 'min_samples_split': 9}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:49,765] Trial 7 finished with value: 15.345530423975926 and parameters: {'n_estimators': 192, 'max_depth': 15, 'min_samples_split': 10}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:51,623] Trial 8 finished with value: 15.217992516589144 and parameters: {'n_estimators': 111, 'max_depth': 14, 'min_samples_split': 8}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:53,890] Trial 9 finished with value: 15.276748169565527 and parameters: {'n_estimators': 181, 'max_depth': 12, 'min_samples_split': 6}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:54,312] Trial 10 finished with value: 15.967732064956527 and parameters: {'n_estimators': 48, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 0 with value: 15.215648183011933.
[I 2024-12-12 13:59:55,237] Trial 11 finished with value: 15.171677335424254 and parameters: {'n_estimators': 97, 'max_depth': 16, 'min_samples_split': 8}. Best is trial 11 with value: 15.171677335424254.
[I 2024-12-12 13:59:56,221] Trial 12 finished with value: 15.222317130657192 and parameters: {'n_estimators': 72, 'max_depth': 16, 'min_samples_split': 8}. Best is trial 11 with value: 15.171677335424254.
[I 2024-12-12 13:59:58,021] Trial 13 finished with value: 15.45198186899619 and parameters: {'n_estimators': 134, 'max_depth': 20, 'min_samples_split': 8}. Best is trial 11 with value: 15.171677335424254.
[I 2024-12-12 13:59:58,826] Trial 14 finished with value: 15.268896259778066 and parameters: {'n_estimators': 87, 'max_depth': 17, 'min_samples_split': 7}. Best is trial 11 with value: 15.171677335424254.
[I 2024-12-12 14:00:00,195] Trial 15 finished with value: 15.137850569508581 and parameters: {'n_estimators': 142, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 15 with value: 15.137850569508581.
[I 2024-12-12 14:00:00,341] Trial 16 finished with value: 17.087384676692018 and parameters: {'n_estimators': 11, 'max_depth': 10, 'min_samples_split': 4}. Best is trial 15 with value: 15.137850569508581.
[I 2024-12-12 14:00:01,869] Trial 17 finished with value: 15.10854989701674 and parameters: {'n_estimators': 147, 'max_depth': 14, 'min_samples_split': 2}. Best is trial 17 with value: 15.10854989701674.
[I 2024-12-12 14:00:03,447] Trial 18 finished with value: 14.918256838338369 and parameters: {'n_estimators': 154, 'max_depth': 13, 'min_samples_split': 2}. Best is trial 18 with value: 14.918256838338369.
[I 2024-12-12 14:00:04,467] Trial 19 finished with value: 19.02084839422958 and parameters: {'n_estimators': 167, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 18 with value: 14.918256838338369.
[I 2024-12-12 14:00:05,912] Trial 20 finished with value: 15.08205230812195 and parameters: {'n_estimators': 153, 'max_depth': 10, 'min_samples_split': 3}. Best is trial 18 with value: 14.918256838338369.
[I 2024-12-12 14:00:07,434] Trial 21 finished with value: 15.06386146346232 and parameters: {'n_estimators': 158, 'max_depth': 10, 'min_samples_split': 2}. Best is trial 18 with value: 14.918256838338369.
[I 2024-12-12 14:00:09,411] Trial 22 finished with value: 15.150817850801383 and parameters: {'n_estimators': 161, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 18 with value: 14.918256838338369.
[I 2024-12-12 14:00:11,063] Trial 23 finished with value: 15.18543061950424 and parameters: {'n_estimators': 124, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 18 with value: 14.918256838338369.
[I 2024-12-12 14:00:12,411] Trial 24 finished with value: 15.340856128065104 and parameters: {'n_estimators': 158, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 18 with value: 14.918256838338369.
[I 2024-12-12 14:00:13,420] Trial 25 finished with value: 15.500221639706108 and parameters: {'n_estimators': 121, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 18 with value: 14.918256838338369.
[I 2024-12-12 14:00:15,047] Trial 26 finished with value: 15.157837786506544 and parameters: {'n_estimators': 169, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 18 with value: 14.918256838338369.
[I 2024-12-12 14:00:16,611] Trial 27 finished with value: 14.890279234297765 and parameters: {'n_estimators': 153, 'max_depth': 13, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:17,957] Trial 28 finished with value: 15.034831763620952 and parameters: {'n_estimators': 129, 'max_depth': 13, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:19,012] Trial 29 finished with value: 15.120791059579593 and parameters: {'n_estimators': 111, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:21,237] Trial 30 finished with value: 14.948749338524511 and parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:24,019] Trial 31 finished with value: 14.934680547688377 and parameters: {'n_estimators': 199, 'max_depth': 13, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:26,049] Trial 32 finished with value: 14.948749338524511 and parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:27,783] Trial 33 finished with value: 15.119225230207885 and parameters: {'n_estimators': 177, 'max_depth': 15, 'min_samples_split': 3}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:29,621] Trial 34 finished with value: 15.12131980386456 and parameters: {'n_estimators': 198, 'max_depth': 12, 'min_samples_split': 4}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:31,405] Trial 35 finished with value: 15.102460927871766 and parameters: {'n_estimators': 173, 'max_depth': 15, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:33,310] Trial 36 finished with value: 15.173784056413613 and parameters: {'n_estimators': 190, 'max_depth': 13, 'min_samples_split': 3}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:35,835] Trial 37 finished with value: 15.379926814049913 and parameters: {'n_estimators': 183, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:37,465] Trial 38 finished with value: 14.929043275526762 and parameters: {'n_estimators': 148, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:38,924] Trial 39 finished with value: 15.052433379536364 and parameters: {'n_estimators': 146, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:40,050] Trial 40 finished with value: 14.981375537505759 and parameters: {'n_estimators': 116, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:42,265] Trial 41 finished with value: 15.100226638189179 and parameters: {'n_estimators': 185, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:44,584] Trial 42 finished with value: 15.127046808797544 and parameters: {'n_estimators': 166, 'max_depth': 14, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:46,750] Trial 43 finished with value: 15.076832181971463 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:49,265] Trial 44 finished with value: 15.11916378253676 and parameters: {'n_estimators': 176, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:50,722] Trial 45 finished with value: 15.008700388933104 and parameters: {'n_estimators': 141, 'max_depth': 15, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:51,728] Trial 46 finished with value: 14.972248305795087 and parameters: {'n_estimators': 101, 'max_depth': 13, 'min_samples_split': 3}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:52,532] Trial 47 finished with value: 15.008513301054165 and parameters: {'n_estimators': 78, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:54,354] Trial 48 finished with value: 15.247876181811431 and parameters: {'n_estimators': 189, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:55,840] Trial 49 finished with value: 15.017555034057612 and parameters: {'n_estimators': 152, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 27 with value: 14.890279234297765.
[I 2024-12-12 14:00:55,841] A new study created in memory with name: no-name-acde7bd4-9290-4698-9fab-c203895b6bb4
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:55,858] Trial 0 finished with value: 24.331245346623085 and parameters: {'alpha': 0.03102892037923343}. Best is trial 0 with value: 24.331245346623085.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:55,873] Trial 1 finished with value: 24.31090005678241 and parameters: {'alpha': 1.515842842333829}. Best is trial 1 with value: 24.31090005678241.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:55,887] Trial 2 finished with value: 24.311700165660163 and parameters: {'alpha': 1.4514413533028903}. Best is trial 1 with value: 24.31090005678241.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:55,902] Trial 3 finished with value: 24.314885839391827 and parameters: {'alpha': 1.2005919900963056}. Best is trial 1 with value: 24.31090005678241.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:55,916] Trial 4 finished with value: 24.33164132781021 and parameters: {'alpha': 0.004824007542382394}. Best is trial 1 with value: 24.31090005678241.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:55,931] Trial 5 finished with value: 24.331049995627883 and parameters: {'alpha': 0.04398915209627844}. Best is trial 1 with value: 24.31090005678241.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:55,946] Trial 6 finished with value: 24.3316903405228 and parameters: {'alpha': 0.0015865863252713587}. Best is trial 1 with value: 24.31090005678241.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:55,963] Trial 7 finished with value: 24.665649265159864 and parameters: {'alpha': 49.00812874989451}. Best is trial 1 with value: 24.31090005678241.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:55,979] Trial 8 finished with value: 24.26335732727861 and parameters: {'alpha': 7.694785861276065}. Best is trial 8 with value: 24.26335732727861.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:55,994] Trial 9 finished with value: 24.331698114543766 and parameters: {'alpha': 0.0010732144879195043}. Best is trial 8 with value: 24.26335732727861.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,014] Trial 10 finished with value: 24.302363557306315 and parameters: {'alpha': 21.816614366235655}. Best is trial 8 with value: 24.26335732727861.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,033] Trial 11 finished with value: 24.759680331515376 and parameters: {'alpha': 54.21397147982392}. Best is trial 8 with value: 24.26335732727861.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)

Optimizing Ridge...

[I 2024-12-12 14:00:56,059] Trial 12 finished with value: 24.26550053231861 and parameters: {'alpha': 7.149639962350158}. Best is trial 8 with value: 24.26335732727861.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,080] Trial 13 finished with value: 24.263071775566594 and parameters: {'alpha': 7.774839177420344}. Best is trial 13 with value: 24.263071775566594.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,103] Trial 14 finished with value: 24.270326173537633 and parameters: {'alpha': 6.156392501281475}. Best is trial 13 with value: 24.263071775566594.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,125] Trial 15 finished with value: 24.32964079389428 and parameters: {'alpha': 0.1381243823754283}. Best is trial 13 with value: 24.263071775566594.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,147] Trial 16 finished with value: 24.259924917814708 and parameters: {'alpha': 8.854928980981542}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,170] Trial 17 finished with value: 24.322527002358502 and parameters: {'alpha': 0.6317176255481962}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,190] Trial 18 finished with value: 24.26802799894572 and parameters: {'alpha': 16.124412558808423}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,218] Trial 19 finished with value: 24.32726188079328 and parameters: {'alpha': 0.29967650370265303}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,240] Trial 20 finished with value: 24.293230716408345 and parameters: {'alpha': 3.1177756460661206}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,264] Trial 21 finished with value: 25.55822523040205 and parameters: {'alpha': 91.4570874742202}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,292] Trial 22 finished with value: 24.261402023417222 and parameters: {'alpha': 14.172083649689007}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,317] Trial 23 finished with value: 24.286386334254303 and parameters: {'alpha': 19.5740677306155}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,341] Trial 24 finished with value: 24.288761199358767 and parameters: {'alpha': 3.5944937722002033}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,367] Trial 25 finished with value: 24.315781995348182 and parameters: {'alpha': 23.448099536364943}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,390] Trial 26 finished with value: 24.327550074752672 and parameters: {'alpha': 0.2799243248265473}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,413] Trial 27 finished with value: 24.30164360700283 and parameters: {'alpha': 2.307376307687205}. Best is trial 16 with value: 24.259924917814708.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,434] Trial 28 finished with value: 24.258176085839875 and parameters: {'alpha': 9.822584251642654}. Best is trial 28 with value: 24.258176085839875.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,460] Trial 29 finished with value: 24.65232682311941 and parameters: {'alpha': 48.24276317187625}. Best is trial 28 with value: 24.258176085839875.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,482] Trial 30 finished with value: 24.32267515912264 and parameters: {'alpha': 0.6211049718365792}. Best is trial 28 with value: 24.258176085839875.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,506] Trial 31 finished with value: 24.26236115059685 and parameters: {'alpha': 7.983760365827417}. Best is trial 28 with value: 24.258176085839875.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,531] Trial 32 finished with value: 24.264424358513555 and parameters: {'alpha': 15.170059482698022}. Best is trial 28 with value: 24.258176085839875.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,555] Trial 33 finished with value: 24.286606350105014 and parameters: {'alpha': 3.838479701982867}. Best is trial 28 with value: 24.258176085839875.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,578] Trial 34 finished with value: 24.31904163696245 and parameters: {'alpha': 0.8858043889663356}. Best is trial 28 with value: 24.258176085839875.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,602] Trial 35 finished with value: 24.30831886556562 and parameters: {'alpha': 1.7276741344769162}. Best is trial 28 with value: 24.258176085839875.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,627] Trial 36 finished with value: 24.33044477931436 and parameters: {'alpha': 0.08427846102081693}. Best is trial 28 with value: 24.258176085839875.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,652] Trial 37 finished with value: 24.257376032769134 and parameters: {'alpha': 10.806505825086797}. Best is trial 37 with value: 24.257376032769134.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,677] Trial 38 finished with value: 24.331420261391393 and parameters: {'alpha': 0.019442719846480737}. Best is trial 37 with value: 24.257376032769134.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,702] Trial 39 finished with value: 25.73009916235106 and parameters: {'alpha': 98.65074265287596}. Best is trial 37 with value: 24.257376032769134.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,728] Trial 40 finished with value: 24.413914404838927 and parameters: {'alpha': 32.54253100597818}. Best is trial 37 with value: 24.257376032769134.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,753] Trial 41 finished with value: 24.257332051717572 and parameters: {'alpha': 11.318356463991519}. Best is trial 41 with value: 24.257332051717572.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,776] Trial 42 finished with value: 24.257576482163188 and parameters: {'alpha': 11.89551263182724}. Best is trial 41 with value: 24.257332051717572.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,808] Trial 43 finished with value: 24.25758611643555 and parameters: {'alpha': 10.406043752998555}. Best is trial 41 with value: 24.257332051717572.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,834] Trial 44 finished with value: 24.281009940253917 and parameters: {'alpha': 4.52502368449297}. Best is trial 41 with value: 24.257332051717572.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,862] Trial 45 finished with value: 24.44528054502659 and parameters: {'alpha': 34.9325745114299}. Best is trial 41 with value: 24.257332051717572.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,888] Trial 46 finished with value: 24.25738033212196 and parameters: {'alpha': 10.793724176404384}. Best is trial 41 with value: 24.257332051717572.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,916] Trial 47 finished with value: 24.312247004112532 and parameters: {'alpha': 1.4077566635389696}. Best is trial 41 with value: 24.257332051717572.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,944] Trial 48 finished with value: 24.33156152993895 and parameters: {'alpha': 0.010097740302786797}. Best is trial 41 with value: 24.257332051717572.
<ipython-input-77-cc86d8864b7f>:45: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha = trial.suggest_loguniform("alpha", 1e-3, 1e2)
[I 2024-12-12 14:00:56,972] Trial 49 finished with value: 24.25754651536021 and parameters: {'alpha': 11.850637403546349}. Best is trial 41 with value: 24.257332051717572.

Best parameters for KNN: {'n_neighbors': 4, 'weights': 'distance', 'p': 1}
Best score for KNN: 15.739524325431393
Best parameters for Random Forest: {'n_estimators': 153, 'max_depth': 13, 'min_samples_split': 2}
Best score for Random Forest: 14.890279234297765
Best parameters for Ridge: {'alpha': 11.318356463991519}
Best score for Ridge: 24.257332051717572

In [ ]:
import joblib
# Save the trained linear regression model
joblib.dump(linreg, 'linear_regression_model.pkl')

['linear_regression_model.pkl']